/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import lab2.ex1.Book;
import lab2.ex2.*;
import lab3.ex2.*;

public class Library {
	public static void main(String arg[]) {
		lab3.ex2.UIApplication.run(arg);
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
